# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Avi Documentation
email: info@avinetworks.com
description: > # this means to ignore newlines until "baseurl:"
  Avi Vantage Product Documentation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kb.avinetworks.com/docs/" # the base hostname & protocol for your site
twitter_username: AviNetworks
github_username:  avinetworks

# Build settings
markdown: kramdown
